SELECT NAME, OPEN_MODE, RESTRICTED FROM V$PDBS;
SHOW CON_NAME; 
ALTER SESSION SET CONTAINER = ORCLPDB;
SELECT NAME, OPEN_MODE FROM V$CONTAINERS; 
ALTER DATABASE OPEN;
ALTER SESSION SET CONTAINER = ORCLPDB; 
ALTER PLUGGABLE DATABASE ORCLPDB OPEN READ WRITE; 
ALTER PLUGGABLE DATABASE ORCLPDB SAVE STATE;
SELECT CDB FROM V$DATABASE;
SELECT NAME, OPEN_MODE FROM V$PDBS WHERE CON_ID > 2; 
ALTER SESSION SET CONTAINER =ORCLPDB;
CREATE USER  UNIVERSITY_USER1 IDENTIFIED BY ORACLE12 
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP 
QUOTA UNLIMITED ON USERS; 
GRANT CONNECT, RESOURCE TO UNIVERSITY_USER1;
CONNECT UNIVERSITY_USER1;
