---FACULTY TABLE
CREATE TABLE FACULTY(
FACU_ID NUMBER PRIMARY KEY,
FACU_NAME VARCHAR2(50),
DEPARTMENT VARCHAR2(50));
---SUBJECT TABLE
CREATE TABLE SUBJECT (
SUBJECT_ID NUMBER PRIMARY KEY,
SUBJECT_NAME VARCHAR2(50),
CREDIT_HOURS NUMBER,FACU_ID NUMBER,
CONSTRAINT FK_SUBJECT_FACULTY FOREIGN KEY(FACU_ID)
REFERENCES  FACULTY(FACU_ID));
---ASSIGNMENT TABLE
CREATE TABLE ASSIGNMENT (
    ASSIGNMENT_ID NUMBER PRIMARY KEY,
    ASSIGNMENT_TITLE VARCHAR2(100),DUE_DATE DATE,
    SUBJECT_ID NUMBER, 
    CONSTRAINT FK_ASSIGNMENT_SUBJECT FOREIGN KEY(SUBJECT_ID)
    REFERENCES SUBJECT(SUBJECT_ID));
    ---INSERT DATA
INSERT INTO FACULTY VALUES (1, 'Ali Raza', 'Computer Science');
INSERT INTO FACULTY VALUES (2, 'Sara Khan', 'Information Technology');
INSERT INTO FACULTY VALUES (3, 'Ahmed Hassan', 'Software Engineering');
INSERT INTO FACULTY VALUES (4, 'Ayesha Malik', 'Computer Science');
INSERT INTO FACULTY VALUES (5, 'Usman Tariq', 'Information Technology');
INSERT INTO FACULTY VALUES (6, 'Hina Aslam', 'Data Science');
INSERT INTO FACULTY VALUES (7, 'Bilal Ahmed', 'Software Engineering');
INSERT INTO FACULTY VALUES (8, 'Maham Iqbal', 'Data Science');
INSERT INTO FACULTY VALUES (9, 'Hamza Shah', 'Computer Science');
INSERT INTO FACULTY VALUES (10, 'Fatima Noor', 'Information Technology');
COMMIT;
    ---INSERT DATA
INSERT INTO SUBJECT VALUES (1, 'Database Systems', 3, 1);
INSERT INTO SUBJECT VALUES (2, 'Web Development', 3, 2);
INSERT INTO SUBJECT VALUES (3, 'Software Engineering', 3, 3);
INSERT INTO SUBJECT VALUES (4, 'Data Structures', 3, 4);
INSERT INTO SUBJECT VALUES (5, 'Operating Systems', 3, 5);
INSERT INTO SUBJECT VALUES (6, 'Data Science', 3, 6);
INSERT INTO SUBJECT VALUES (7, 'Computer Networks', 3, 7);
INSERT INTO SUBJECT VALUES (8, 'Artificial Intelligence', 3, 8);
INSERT INTO SUBJECT VALUES (9, 'Programming Fundamentals', 3, 9);
INSERT INTO SUBJECT VALUES (10, 'Information Security', 3, 10);
COMMIT;
--INSERT DATA
INSERT INTO ASSIGNMENT VALUES (1, 'Database Design', DATE '2026-10-10', 1);
INSERT INTO ASSIGNMENT VALUES (2, 'HTML CSS Project', DATE '2026-10-12', 2);
INSERT INTO ASSIGNMENT VALUES (3, 'Software Development Report', DATE '2026-10-14', 3);
INSERT INTO ASSIGNMENT VALUES (4, 'Stack and Queue', DATE '2026-10-16', 4);
INSERT INTO ASSIGNMENT VALUES (5, 'Process Management', DATE '2026-10-18', 5);
INSERT INTO ASSIGNMENT VALUES (6, 'Data Analysis Task', DATE '2026-10-20', 6);
INSERT INTO ASSIGNMENT VALUES (7, 'Network Configuration', DATE '2026-10-22', 7);
INSERT INTO ASSIGNMENT VALUES (8, 'AI Research Report', DATE '2026-10-24', 8);
INSERT INTO ASSIGNMENT VALUES (9, 'C Programming Task', DATE '2026-10-26', 9);
INSERT INTO ASSIGNMENT VALUES (10, 'Cyber Security Report', DATE '2026-10-28', 10);
COMMIT;
SELECT *FROM FACULTY;
SELECT * FROM SUBJECT;
SELECT *FROM ASSIGNMENT; 
UPDATE ASSIGNMENT SET DUE_DATE = DATE '2026-10-11'  WHERE ASSIGNMENT_ID = 3;
ROLLBACK;
SAVEPOINT SPL; 
DELETE FROM ASSIGNMENT WHERE  DUE_DATE = DATE '2026-10-11';
ROLLBACK TO SPL;
GRANT SELECT, INSERT, UPDATE ON FACULTY TO HR;
REVOKE INSERT ON FACULTY FROM HR; 
SELECT FACU_NAME, DEPARTMENT FROM FACULTY WHERE DEPARTMENT = 'Computer Science';
SELECT F.FACU_ID,
       F.FACU_NAME,
       F.DEPARTMENT,
       S.SUBJECT_ID,
       S.SUBJECT_NAME
FROM FACULTY F
JOIN SUBJECT S
ON F.FACU_ID = S.FACU_ID;
SELECT DEPARTMENT, COUNT(FACU_ID)AS TOTAL_FACULTY 
FROM FACULTY 
GROUP BY DEPARTMENT;